version: '3.8'
services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - /home/mycommunity/v2ray/api-config.json:/etc/v2ray/config.json
    ports:
      - "127.0.0.1:10086:10086"
      - "127.0.0.1:10085:10085"
    command: run -c /etc/v2ray/config.json

